version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./code/project:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network
    app:
        image: php:8.1-fpm
        container_name: php
        volumes:
            - ./code:/var/www
        networks:
            - app-network
    redis:
        image: redis:alpine
        container_name: redis
        volumes:
            - ./docker-volumes/redis:/data
        ports:
            - "6380:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
