version: '3.8'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network
    app:
        image: php:8.1-fpm
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./code:/var/www
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
